LABELS = {'person': 'person', 
          'bicycle': 'bicycle', 
          'car': 'car', 
          'motorcycle': 'motorcycle', 
          'airplane': 'airplane', 
          'bus': 'bus', 
          'train': 'train', 
          'truck': 'truck', 
          'boat': 'boat', 
          'traffic light': 'traffic-light', 
          'fire hydrant': 'fire-hydrant', 
          'stop sign': 'stop-sign', 
          'parking meter': 'parking-meter',
          'bench': 'bench', 
          'cat': 'cat', 
          'dog': 'dog', 
          'horse': 'horse', 
          'sheep': 'sheep', 
          'cow': 'cow', 
          'backpack': 'backpack', 
          'umbrella': 'umbrella', 
          'handbag': 'handbag', 
          'tie': 'tie', 
          'suitcase': 'suitcase', 
          'frisbee': 'frisbee', 
          'skis': 'skis', 
          'snowboard': 'snowboard', 
          'sports ball': 'sports-ball', 
          'kite': 'kite', 
          'baseball bat': 'baseball-bat', 
          'baseball glove': 'baseball-glove', 
          'skateboard': 'skateboard', 
          'surfboard': 'surfboard', 
          'tennis racket': 'tennis-racket', 
          'bottle': 'bottle', 
          'wine glass': 'wine-glass', 
          'cup': 'cup', 
          'fork': 'fork', 
          'knife': 'knife', 
          'spoon': 'spoon', 
          'bowl': 'bowl', 
          'banana': 'banana', 
          'apple': 'apple', 
          'sandwich': 'sandwich', 
          'orange': 'orange', 
          'broccoli': 'broccoli', 
          'carrot': 'carrot', 
          'hot dog': 'hot dog', 
          'pizza': 'pizza', 
          'donut': 'donut', 
          'cake': 'cake', 
          'chair': 'chair', 
          'couch': 'couch', 
          'potted plant': 'potted-plant', 
          'bed': 'bed', 
          'dining table': 'dining-table', 
          'toilet': 'toilet', 
          'tv': 'tv', 
          'laptop': 'laptop', 
          'mouse': 'mouse', 
          'remote': 'remote', 
          'keyboard': 'keyboard', 
          'cell phone': 'cell-phone', 
          'microwave': 'microwave', 
          'oven': 'oven', 
          'toaster': 'toaster', 
          'sink': 'sink', 
          'refrigerator': 'refrigerator', 
          'book': 'book', 
          'clock': 'clock', 
          'vase': 'vase', 
          'scissors': 'scissors', 
          'teddy bear': 'teddy bear', 
          'hair drier': 'hair drier', 
          'toothbrush': 'toothbrush', 
          'find': 'find', 
          'list': 'list', 
          'mute': 'mute', 
          'continue': 'continue', 
          'close': 'close'}

INITIAL_PROMPT = "person, bicycle, car, motorcycle, airplane, bus, train, truck, boat, traffic light, fire hydrant, stop sign, parking meter, bench, cat, dog, horse, sheep, cow, backpack, umbrella, handbag, tie, suitcase, frisbee, skis, snowboard, sports ball, kite, baseball bat, baseball glove, skateboard, surfboard, tennis racket, bottle, wine glass, cup, fork, knife, spoon, bowl, banana, apple, sandwich, orange, broccoli, carrot, hot dog, pizza, donut, cake, chair, couch, potted plant, bed, dining table, toilet, tv, laptop, mouse, remote, keyboard, cell phone, microwave, oven, toaster, sink, refrigerator, book, clock, vase, scissors, teddy bear, hair drier, toothbrush, find, list, mute, continue, close"