LABELS = {
    "Person": "person",
    "Sneakers": "sneaker",
    "Chair": "chair",
    "Other Shoes": "shoes",
    "Hat": "hat",
    "Car": "car",
    "Lamp": "lamp",
    "Glasses": "glasses",
    "Bottle": "bottle",
    "Desk": "desk",
    "Cup": "cup",
    "Street Lights": "street lights",
    "Cabinet/shelf": "shelf",
    "Handbag/Satchel": "bag",
    "Bracelet": "bracelet",
    "Plate": "plate",
    "Picture/Frame": "picture",
    "Helmet": "helmet",
    "Book": "book",
    "Gloves": "gloves",
    "Storage box": "storage box",
    "Boat": "boat",
    "Leather Shoes": "shoes",
    "Flower": "flower",
    "Bench": "bench",
    "Potted Plant": "potted plant",
    "Bowl/Basin": "bowl",
    "Flag": "flag",
    "Pillow": "pillow",
    "Boots": "boots",
    "Vase": "vase",
    "Microphone": "microphone",
    "Necklace": "necklace",
    "Ring": "ring",
    "SUV": "suv",
    "Wine Glass": "wine glass",
    "Belt": "belt",
    "Monitor/TV": "tv",
    "Backpack": "backpack",
    "Umbrella": "umbrella",
    "Traffic Light": "traffic light",
    "Speaker": "speaker",
    "Watch": "watch",
    "Tie": "tie",
    "Trash bin Can": "trash can",
    "Slippers": "slippers",
    "Bicycle": "bicycle",
    "Stool": "stool",
    "Barrel/bucket": "bucket",
    "Van": "van",
    "Couch": "couch",
    "Sandals": "sandals",
    "Basket": "basket",
    "Drum": "drum",
    "Pen/Pencil": "pen",
    "Bus": "bus",
    "Wild Bird": "bird",
    "High Heels": "high heels",
    "Motorcycle": "motorcycle",
    "Guitar": "guitar",
    "Carpet": "carpet",
    "Cell Phone": "cell phone",
    "Bread": "bread",
    "Camera": "camera",
    "Canned": "canned",
    "Truck": "truck",
    "Traffic cone": "traffic cone",
    "Cymbal": "cymbal",
    "Lifesaver": "lifesaver",
    "Towel": "towel",
    "Stuffed Toy": "stuffed toy",
    "Candle": "candle",
    "Sailboat": "sailboat",
    "Laptop": "laptop",
    "Awning": "awning",
    "Bed": "bed",
    "Faucet": "faucet",
    "Tent": "tent",
    "Horse": "horse",
    "Mirror": "mirror",
    "Power outlet": "power outlet",
    "Sink": "sink", 
    "Apple": "apple",
    "Air Conditioner": "air conditioner",
    "Knife": "knife",
    "Hockey Stick": "hockey stick",
    "Paddle": "paddle",
    "Pickup Truck": "truck",
    "Fork": "fork",
    "Traffic Sign": "traffic sign",
    "Balloon": "balloon",
    "Tripod": "tripod",
    "Dog": "dog",
    "Spoon": "spoon",
    "Clock": "clock",
    "Pot": "pot",
    "Cow": "cow",
    "Cake": "cake",
    "Dinning Table": "dinning table",
    "Sheep": "sheep",
    "Hanger": "hanger",
    "Blackboard/Whiteboard": "whiteboard",
    "Napkin": "napkin",
    "Other Fish": "fish",
    "Orange/Tangerine": "orange",
    "Toiletry": "toiletry",
    "Keyboard": "keyboard",
    "Tomato": "tomato",
    "Lantern": "lantern",
    "Machinery Vehicle": "machinery vehicle",
    "Fan": "fan",
    "Green Vegetables": "vegetables",
    "Banana": "banana",
    "Baseball Glove": "baseball glove",
    "Airplane": "airplane",
    "Mouse": "mouse",
    "Train": "train",
    "Pumpkin": "pumpkin",
    "Soccer": "soccer",
    "Skiboard": "skiboard",
    "Luggage": "luggage",
    "Nightstand": "nightstand",
    "Tea pot": "tea pot",
    "Telephone": "telephone",
    "Trolley": "trolley",
    "Head Phone": "head phone",
    "Sports Car": "sports car",
    "Stop Sign": "stop sign",
    "Dessert": "dessert",
    "Scooter": "scooter",
    "Stroller": "stroller",
    "Crane": "crane",
    "Remote": "remote",
    "Refrigerator": "refrigerator",
    "Oven": "oven",
    "Lemon": "lemon",
    "Duck": "duck",
    "Baseball Bat": "baseball bat",
    "Surveillance Camera": "surveillance camera",
    "Cat": "cat",
    "Jug": "jug",
    "Broccoli": "broccoli",
    "Piano": "piano",
    "Pizza": "pizza",
    "Elephant": "elephant",
    "Skateboard": "skateboard",
    "Surfboard": "surfboard",
    "Gun": "gun",
    "Skating and Skiing shoes": "skating and skiing shoes",
    "Gas stove": "gas stove",
    "Donut": "donut",
    "Bow Tie": "bow tie",
    "Carrot": "carrot",
    "Toilet": "toilet",
    "Kite": "kite",
    "Strawberry": "strawberry",
    "Other Balls": "ball",
    "Shovel": "shovel",
    "Pepper": "pepper",
    "Computer Box": "computer box",
    "Toilet Paper": "toilet paper",
    "Cleaning Products": "cleaning products",
    "Chopsticks": "chopsticks",
    "Microwave": "microwave",
    "Pigeon": "pigeon",
    "Baseball": "baseball",
    "Cutting/chopping Board": "chopping board",
    "Coffee Table": "coffee table",
    "Side Table": "side table",
    "Scissors": "scissors",
    "Marker": "marker",
    "Pie": "pie",
    "Ladder": "ladder",
    "Snowboard": "snowboard",
    "Cookies": "cookies",
    "Radiator": "radiator",
    "Fire Hydrant": "fire hydrant",
    "Basketball": "basketball",
    "Zebra": "zebra",
    "Grape": "grape",
    "Giraffe": "giraffe",
    "Potato": "potato",
    "Sausage": "sausage",
    "Tricycle": "tricycle",
    "Violin": "violin",
    "Egg": "egg",
    "Fire Extinguisher": "fire extinguisher",
    "Candy": "candy",
    "Fire Truck": "fire truck",
    "Billiards": "billiards",
    "Converter": "converter",
    "Bathtub": "bathtub",
    "Wheelchair": "wheelchair",
    "Golf Club": "golf club",
    "Briefcase": "briefcase",
    "Cucumber": "cucumber",
    "Cigar/Cigarette": "cigarette",
    "Paint Brush": "paint brush",
    "Pear": "pear",
    "Heavy Truck": "heavy truck",
    "Hamburger": "hamburger",
    "Extractor": "extractor",
    "Extension Cord": "extension cord",
    "Tong": "tong",
    "Tennis Racket": "tennis racket",
    "Folder": "folder",
    "American Football": "american football",
    "earphone": "earphone",
    "Mask": "mask",
    "Kettle": "kettle",
    "Tennis": "tennis",
    "Ship": "ship",
    "Swing": "swing",
    "Coffee Machine": "coffee machine",
    "Slide": "slide",
    "Carriage": "carriage",
    "Onion": "onion",
    "Green beans": "green beans",
    "Projector": "projector",
    "Frisbee": "frisbee",
    "Washing Machine/Drying Machine": "laundry machine",
    "Chicken": "chicken",
    "Printer": "printer",
    "Watermelon": "watermelon",
    "Saxophone": "saxophone",
    "Tissue": "tissue",
    "Toothbrush": "toothbrush",
    "Ice cream": "ice cream",
    "Hot-air balloon": "hot air balloon",
    "Cello": "cello",
    "French Fries": "french fries",
    "Scale": "scale",
    "Trophy": "trophy",
    "Cabbage": "cabbage",
    "Hot dog": "hot dog",
    "Blender": "blender",
    "Peach": "peach",
    "Rice": "rice",
    "Wallet/Purse": "purse",
    "Volleyball": "volleyball",
    "Deer": "deer",
    "Goose": "goose",
    "Tape": "tape",
    "Tablet": "tablet",
    "Cosmetics": "cosmetics",
    "Trumpet": "trumpet",
    "Pineapple": "pineapple",
    "Golf Ball": "golf ball",
    "Ambulance": "ambulance",
    "Parking meter": "parking meter",
    "Mango": "mango",
    "Key": "key",
    "Hurdle": "hurdle",
    "Fishing Rod": "fishing rod",
    "Medal": "medal",
    "Flute": "flute",
    "Brush": "brush",
    "Penguin": "penguin",
    "Megaphone": "megaphone",
    "Corn": "corn",
    "Lettuce": "lettuce",
    "Garlic": "garlic",
    "Swan": "swan",
    "Helicopter": "helicopter",
    "Green Onion": "green onion",
    "Sandwich": "sandwich",
    "Nuts": "nuts",
    "Speed Limit Sign": "speed limit sign",
    "Induction Cooker": "induction cooker",
    "Broom": "broom",
    "Trombone": "trombone",
    "Plum": "plum",
    "Rickshaw": "rickshaw",
    "Goldfish": "goldfish",
    "Kiwi fruit": "kiwi fruit",
    "Router/modem": "modem",
    "Poker Card": "poker card",
    "Toaster": "toaster",
    "Shrimp": "shrimp",
    "Sushi": "sushi",
    "Cheese": "cheese",
    "Notepaper": "notepaper",
    "Cherry": "cherry",
    "Pliers": "pliers",
    "CD": "cd",
    "Pasta": "pasta",
    "Hammer": "hammer",
    "Cue": "cue",
    "Avocado": "avocado",
    "Hamimelon": "hamimelon",
    "Flask": "flask",
    "Mushroom": "mushroom",
    "Screwdriver": "screwdriver",
    "Soap": "soap",
    "Recorder": "recorder",
    "Bear": "bear",
    "Eggplant": "eggplant",
    "Board Eraser": "board eraser",
    "Coconut": "coconut",
    "Tape Measure/Ruler": "ruler",
    "Pig": "pig",
    "Showerhead": "showerhead",
    "Globe": "globe",
    "Chips": "chips",
    "Steak": "steak",
    "Crosswalk Sign": "crosswalk sign",
    "Stapler": "stapler",
    "Camel": "camel",
    "Formula 1": "car",
    "Pomegranate": "pomegranate",
    "Dishwasher": "dishwasher",
    "Crab": "crab",
    "Hoverboard": "hoverboard",
    "Meat ball": "meat ball",
    "Rice Cooker": "rice cooker",
    "Tuba": "tuba",
    "Calculator": "calculator",
    "Papaya": "papaya",
    "Antelope": "antelope",
    "Parrot": "parrot",
    "Seal": "seal",
    "Butterfly": "butterfly",
    "Dumbbell": "dumbbell",
    "Donkey": "donkey",
    "Lion": "lion",
    "Urinal": "urinal",
    "Dolphin": "dolphin",
    "Electric Drill": "electric drill",
    "Hair Dryer": "hair dryer",
    "Egg tart": "egg tart",
    "Jellyfish": "jellyfish",
    "Treadmill": "treadmill",
    "Lighter": "lighter",
    "Grapefruit": "grapefruit",
    "Game board": "game_board",
    "Mop": "mop",
    "Radish": "radish",
    "Baozi": "baozi",
    "Target": "target",
    "French": "french",
    "Spring Rolls": "spring rolls",
    "Monkey": "monkey",
    "Rabbit": "rabbit",
    "Pencil Case": "pencil case",
    "Yak": "yak",
    "Red Cabbage": "red cabbage",
    "Binoculars": "binoculars",
    "Asparagus": "asparagus",
    "Barbell": "barbell",
    "Scallop": "scallop",
    "Noddles": "noddles",
    "Comb": "comb",
    "Dumpling": "dumpling",
    "Oyster": "oyster",
    "Table Tennis paddle": "table tennis paddle",
    "Cosmetics Brush/Eyeliner Pencil": "cosmetics",
    "Chainsaw": "chainsaw",
    "Eraser": "eraser",
    "Lobster": "lobster",
    "Durian": "durian",
    "Okra": "okra",
    "Lipstick": "lipstick",
    "Cosmetics Mirror": "cosmetics mirror",
    "Curling": "curling",
    "Table Tennis": "table tennis",
    'find': 'find', 
    'list': 'list', 
    'mute': 'mute', 
    'continue': 'continue', 
    'close': 'close'
}

PLURALS = {
    'Person': 'people',
    'Sneakers': 'sneakers',
    'Chair': 'chairs',
    'Other Shoes': 'shoes',
    'Hat': 'hats',
    'Car': 'cars',
    'Lamp': 'lamps',
    'Glasses': 'glass',
    'Bottle': 'bottles',
    'Desk': 'desks',
    'Cup': 'cups',
    'Street Lights': 'street lights',
    'Cabinet/shelf': 'shelves',
    'Handbag/Satchel': 'bags',
    'Bracelet': 'bracelets',
    'Plate': 'plates',
    'Picture/Frame': 'pictures',
    'Helmet': 'helmets',
    'Book': 'books',
    'Gloves': 'gloves',
    'Storage box': 'storage boxes',
    'Boat': 'boats',
    'Leather Shoes': 'leather shoe',
    'Flower': 'flowers',
    'Bench': 'benches',
    'Potted Plant': 'potted plants',
    'Bowl/Basin': 'bowls',
    'Flag': 'flags',
    'Pillow': 'pillows',
    'Boots': 'boots',
    'Vase': 'vases',
    'Microphone': 'microphones',
    'Necklace': 'necklaces',
    'Ring': 'rings',
    'SUV': 'suvs',
    'Wine Glass': 'wine glasses',
    'Belt': 'belts',
    'Monitor/TV': 'tvs',
    'Backpack': 'backpacks',
    'Umbrella': 'umbrellas',
    'Traffic Light': 'traffic lights',
    'Speaker': 'speakers',
    'Watch': 'watches',
    'Tie': 'ties',
    'Trash bin Can': 'trash cans',
    'Slippers': 'slipper',
    'Bicycle': 'bicycles',
    'Stool': 'stools',
    'Barrel/bucket': 'buckets',
    'Van': 'vans',
    'Couch': 'couches',
    'Sandals': 'sandal',
    'Basket': 'baskets',
    'Drum': 'drums',
    'Pen/Pencil': 'pens',
    'Bus': 'buses',
    'Wild Bird': 'birds',
    'High Heels': 'high_heel',
    'Motorcycle': 'motorcycles',
    'Guitar': 'guitars',
    'Carpet': 'carpets',
    'Cell Phone': 'cell phones',
    'Bread': 'breads',
    'Camera': 'cameras',
    'Canned': 'canneds',
    'Truck': 'trucks',
    'Traffic cone': 'traffic cones',
    'Cymbal': 'cymbals',
    'Lifesaver': 'lifesavers',
    'Towel': 'towels',
    'Stuffed Toy': 'stuffed toys',
    'Candle': 'candles',
    'Sailboat': 'sailboats',
    'Laptop': 'laptops',
    'Awning': 'awnings',
    'Bed': 'beds',
    'Faucet': 'faucets',
    'Tent': 'tents',
    'Horse': 'horses',
    'Mirror': 'mirrors',
    'Power outlet': 'power outlets',
    'Sink': 'sinks',
    'Apple': 'apples',
    'Air Conditioner': 'air conditioners',
    'Knife': 'knives',
    'Hockey Stick': 'hockey sticks',
    'Paddle': 'paddles',
    'Pickup Truck': 'trucks',
    'Fork': 'forks',
    'Traffic Sign': 'traffic signs',
    'Balloon': 'balloons',
    'Tripod': 'tripods',
    'Dog': 'dogs',
    'Spoon': 'spoons',
    'Clock': 'clocks',
    'Pot': 'pots',
    'Cow': 'cows',
    'Cake': 'cakes',
    'Dinning Table': 'dinning tables',
    'Sheep': 'sheep',
    'Hanger': 'hangers',
    'Blackboard/Whiteboard': 'whiteboards',
    'Napkin': 'napkins',
    'Other Fish': 'fish',
    'Orange/Tangerine': 'oranges',
    'Toiletry': 'toiletries',
    'Keyboard': 'keyboards',
    'Tomato': 'tomatoes',
    'Lantern': 'lanterns',
    'Machinery Vehicle': 'machinery vehicles',
    'Fan': 'fans',
    'Green Vegetables': 'vegetable',
    'Banana': 'bananas',
    'Baseball Glove': 'baseball gloves',
    'Airplane': 'airplanes',
    'Mouse': 'mice',
    'Train': 'trains',
    'Pumpkin': 'pumpkins',
    'Soccer': 'soccers',
    'Skiboard': 'skiboards',
    'Luggage': 'luggages',
    'Nightstand': 'nightstands',
    'Tea pot': 'tea pots',
    'Telephone': 'telephones',
    'Trolley': 'trolleys',
    'Head Phone': 'head phones',
    'Sports Car': 'sports cars',
    'Stop Sign': 'stop signs',
    'Dessert': 'desserts',
    'Scooter': 'scooters',
    'Stroller': 'strollers',
    'Crane': 'cranes',
    'Remote': 'remotes',
    'Refrigerator': 'refrigerators',
    'Oven': 'ovens',
    'Lemon': 'lemons',
    'Duck': 'ducks',
    'Baseball Bat': 'baseball bats',
    'Surveillance Camera': 'surveillance cameras',
    'Cat': 'cats',
    'Jug': 'jugs',
    'Broccoli': 'broccolis',
    'Piano': 'pianos',
    'Pizza': 'pizzas',
    'Elephant': 'elephants',
    'Skateboard': 'skateboards',
    'Surfboard': 'surfboards',
    'Gun': 'guns',
    'Skating and Skiing shoes': 'skating and skiing shoes',
    'Gas stove': 'gas stoves',
    'Donut': 'donuts',
    'Bow Tie': 'bow ties',
    'Carrot': 'carrots',
    'Toilet': 'toilets',
    'Kite': 'kites',
    'Strawberry': 'strawberries',
    'Other Balls': 'ball',
    'Shovel': 'shovels',
    'Pepper': 'peppers',
    'Computer Box': 'computer',
    'Toilet Paper': 'toilet papers',
    'Cleaning Products': 'cleaning products',
    'Chopsticks': 'chopstick',
    'Microwave': 'microwaves',
    'Pigeon': 'pigeons',
    'Baseball': 'baseballs',
    'Cutting/chopping Board': 'chopping boards',
    'Coffee Table': 'coffee tables',
    'Side Table': 'side tables',
    'Scissors': 'scissors',
    'Marker': 'markers',
    'Pie': 'pies',
    'Ladder': 'ladders',
    'Snowboard': 'snowboards',
    'Cookies': 'cooky',
    'Radiator': 'radiators',
    'Fire Hydrant': 'fire hydrants',
    'Basketball': 'basketballs',
    'Zebra': 'zebras',
    'Grape': 'grapes',
    'Giraffe': 'giraffes',
    'Potato': 'potatoes',
    'Sausage': 'sausages',
    'Tricycle': 'tricycles',
    'Violin': 'violins',
    'Egg': 'eggs',
    'Fire Extinguisher': 'fire extinguishers',
    'Candy': 'candies',
    'Fire Truck': 'fire trucks',
    'Billiards': 'billiard',
    'Converter': 'converters',
    'Bathtub': 'bathtubs',
    'Wheelchair': 'wheelchairs',
    'Golf Club': 'golf clubs',
    'Briefcase': 'briefcases',
    'Cucumber': 'cucumbers',
    'Cigar/Cigarette': 'cigarettes',
    'Paint Brush': 'paint brushes',
    'Pear': 'pears',
    'Heavy Truck': 'heavy trucks',
    'Hamburger': 'hamburgers',
    'Extractor': 'extractors',
    'Extension Cord': 'extension cords',
    'Tong': 'tongs',
    'Tennis Racket': 'tennis rackets',
    'Folder': 'folders',
    'American Football': 'american footballs',
    'earphone': 'earphones',
    'Mask': 'masks',
    'Kettle': 'kettles',
    'Tennis': 'tenni',
    'Ship': 'ships',
    'Swing': 'swings',
    'Coffee Machine': 'coffee machines',
    'Slide': 'slides',
    'Carriage': 'carriages',
    'Onion': 'onions',
    'Green beans': 'green bean',
    'Projector': 'projectors',
    'Frisbee': 'frisbees',
    'Washing Machine/Drying Machine': 'laundry machines',
    'Chicken': 'chickens',
    'Printer': 'printers',
    'Watermelon': 'watermelons',
    'Saxophone': 'saxophones',
    'Tissue': 'tissues',
    'Toothbrush': 'toothbrushes',
    'Ice cream': 'icecreams',
    'Hot-air balloon': 'hot-air balloons',
    'Cello': 'cellos',
    'French Fries': 'french fries',
    'Scale': 'scales',
    'Trophy': 'trophies',
    'Cabbage': 'cabbages',
    'Hot dog': 'hotdogs',
    'Blender': 'blenders',
    'Peach': 'peaches',
    'Rice': 'rices',
    'Wallet/Purse': 'purses',
    'Volleyball': 'volleyballs',
    'Deer': 'deer',
    'Goose': 'geese',
    'Tape': 'tapes',
    'Tablet': 'tablets',
    'Cosmetics': 'cosmetics',
    'Trumpet': 'trumpets',
    'Pineapple': 'pineapples',
    'Golf Ball': 'golf balls',
    'Ambulance': 'ambulances',
    'Parking meter': 'parking meters',
    'Mango': 'mangoes',
    'Key': 'keys',
    'Hurdle': 'hurdles',
    'Fishing Rod': 'fishing rods',
    'Medal': 'medals',
    'Flute': 'flutes',
    'Brush': 'brushes',
    'Penguin': 'penguins',
    'Megaphone': 'megaphones',
    'Corn': 'corns',
    'Lettuce': 'lettuces',
    'Garlic': 'garlics',
    'Swan': 'swans',
    'Helicopter': 'helicopters',
    'Green Onion': 'green onions',
    'Sandwich': 'sandwiches',
    'Nuts': 'nut',
    'Speed Limit Sign': 'speed limit signs',
    'Induction Cooker': 'induction cookers',
    'Broom': 'brooms',
    'Trombone': 'trombones',
    'Plum': 'plums',
    'Rickshaw': 'rickshaws',
    'Goldfish': 'goldfish',
    'Kiwi fruit': 'kiwi fruits',
    'Router/modem': 'modems',
    'Poker Card': 'poker cards',
    'Toaster': 'toasters',
    'Shrimp': 'shrimps',
    'Sushi': 'sushis',
    'Cheese': 'cheeses',
    'Notepaper': 'notepapers',
    'Cherry': 'cherries',
    'Pliers': 'pliers',
    'CD': 'cds',
    'Pasta': 'pastas',
    'Hammer': 'hammers',
    'Cue': 'cues',
    'Avocado': 'avocados',
    'Hamimelon': 'hamimelons',
    'Flask': 'flasks',
    'Mushroom': 'mushrooms',
    'Screwdriver': 'screwdrivers',
    'Soap': 'soaps',
    'Recorder': 'recorders',
    'Bear': 'bears',
    'Eggplant': 'eggplants',
    'Board Eraser': 'board erasers',
    'Coconut': 'coconuts',
    'Tape Measure/Ruler': 'rulers',
    'Pig': 'pigs',
    'Showerhead': 'showerheads',
    'Globe': 'globes',
    'Chips': 'chip',
    'Steak': 'steaks',
    'Crosswalk Sign': 'crosswalk signs',
    'Stapler': 'staplers',
    'Camel': 'camels',
    'Formula 1': 'formula1',
    'Pomegranate': 'pomegranates',
    'Dishwasher': 'dishwashers',
    'Crab': 'crabs',
    'Hoverboard': 'hoverboards',
    'Meat ball': 'meatballs',
    'Rice Cooker': 'rice cookers',
    'Tuba': 'tubas',
    'Calculator': 'calculators',
    'Papaya': 'papayas',
    'Antelope': 'antelopes',
    'Parrot': 'parrots',
    'Seal': 'seals',
    'Butterfly': 'butterflies',
    'Dumbbell': 'dumbbells',
    'Donkey': 'donkeys',
    'Lion': 'lions',
    'Urinal': 'urinals',
    'Dolphin': 'dolphins',
    'Electric Drill': 'electric drills',
    'Hair Dryer': 'hair dryers',
    'Egg tart': 'egg tarts',
    'Jellyfish': 'jellyfish',
    'Treadmill': 'treadmills',
    'Lighter': 'lighters',
    'Grapefruit': 'grapefruits',
    'Game board': 'game boards',
    'Mop': 'mops',
    'Radish': 'radishes',
    'Baozi': 'baozis',
    'Target': 'targets',
    'French': 'frenches',
    'Spring Rolls': 'springrolls',
    'Monkey': 'monkeys',
    'Rabbit': 'rabbits',
    'Pencil Case': 'pencil cases',
    'Yak': 'yaks',
    'Red Cabbage': 'red cabbages',
    'Binoculars': 'binocular',
    'Asparagus': 'asparaguses',
    'Barbell': 'barbells',
    'Scallop': 'scallops',
    'Noddles': 'noddles',
    'Comb': 'combs',
    'Dumpling': 'dumplings',
    'Oyster': 'oysters',
    'Table Tennis paddle': 'table_tennis_paddles',
    'Cosmetics Brush/Eyeliner Pencil': 'cosmetics',
    'Chainsaw': 'chainsaws',
    'Eraser': 'erasers',
    'Lobster': 'lobsters',
    'Durian': 'durians',
    'Okra': 'okras',
    'Lipstick': 'lipsticks',
    'Cosmetics Mirror': 'cosmetics mirrors',
    'Curling': 'curlings',
    'Table Tennis': 'table tennis'
}



INITIAL_PROMPT = """
Person, Sneakers, Chair, Other Shoes, Hat, Car, Lamp, Glasses, Bottle, Desk, Cup, Street Lights, Cabinet/shelf, Handbag/Satchel, Bracelet, Plate, Picture/Frame, Helmet, Book, Gloves,
Storage box, Boat, Leather Shoes, Flower, Bench, Potted Plant, Bowl/Basin, Flag, Pillow, Boots, Vase, Microphone, Necklace, Ring, SUV, Wine Glass, Belt, Monitor/TV, Backpack, Umbrella,
Traffic Light, Speaker, Watch, Tie, Trash bin Can, Slippers, Bicycle, Stool, Barrel/bucket, Van, Couch, Sandals, Basket, Drum, Pen/Pencil, Bus, Wild Bird, High Heels, Motorcycle, Guitar,
Carpet, Cell Phone, Bread, Camera, Canned, Truck, Traffic cone, Cymbal, Lifesaver, Towel, Stuffed Toy, Candle, Sailboat, Laptop, Awning, Bed, Faucet, Tent, Horse, Mirror, Power outlet,
Sink, Apple, Air Conditioner, Knife, Hockey Stick, Paddle, Pickup Truck, Fork, Traffic Sign, Balloon, Tripod, Dog, Spoon, Clock, Pot, Cow, Cake, Dinning Table, Sheep, Hanger, Blackboard/Whiteboard,
Napkin, Other Fish, Orange/Tangerine, Toiletry, Keyboard, Tomato, Lantern, Machinery Vehicle, Fan, Green Vegetables, Banana, Baseball Glove, Airplane, Mouse, Train, Pumpkin, Soccer, Skiboard,
Luggage, Nightstand, Tea pot, Telephone, Trolley, Head Phone, Sports Car, Stop Sign, Dessert, Scooter, Stroller, Crane, Remote, Refrigerator, Oven, Lemon, Duck, Baseball Bat, Surveillance Camera,
Cat, Jug, Broccoli, Piano, Pizza, Elephant, Skateboard, Surfboard, Gun, Skating and Skiing shoes, Gas stove, Donut, Bow Tie, Carrot, Toilet, Kite, Strawberry, Other Balls, Shovel, Pepper,
Computer Box, Toilet Paper, Cleaning Products, Chopsticks, Microwave, Pigeon, Baseball, Cutting/chopping Board, Coffee Table, Side Table, Scissors, Marker, Pie, Ladder, Snowboard, Cookies,
Radiator, Fire Hydrant, Basketball, Zebra, Grape, Giraffe, Potato, Sausage, Tricycle, Violin, Egg, Fire Extinguisher, Candy, Fire Truck, Billiards, Converter, Bathtub, Wheelchair, Golf Club,
Briefcase, Cucumber, Cigar/Cigarette, Paint Brush, Pear, Heavy Truck, Hamburger, Extractor, Extension Cord, Tong, Tennis Racket, Folder, American Football, earphone, Mask, Kettle, Tennis, Ship,
Swing, Coffee Machine, Slide, Carriage, Onion, Green beans, Projector, Frisbee, Washing Machine/Drying Machine, Chicken, Printer, Watermelon, Saxophone, Tissue, Toothbrush, Ice cream, Hot-air balloon,
Cello, French Fries, Scale, Trophy, Cabbage, Hot dog, Blender, Peach, Rice, Wallet/Purse, Volleyball, Deer, Goose, Tape, Tablet, Cosmetics, Trumpet, Pineapple, Golf Ball, Ambulance, Parking meter,
Mango, Key, Hurdle, Fishing Rod, Medal, Flute, Brush, Penguin, Megaphone, Corn, Lettuce, Garlic, Swan, Helicopter, Green Onion, Sandwich, Nuts, Speed Limit Sign, Induction Cooker, Broom, Trombone,
Plum, Rickshaw, Goldfish, Kiwi fruit, Router/modem, Poker Card, Toaster, Shrimp, Sushi, Cheese, Notepaper, Cherry, Pliers, CD, Pasta, Hammer, Cue, Avocado, Hamimelon, Flask, Mushroom, Screwdriver,
Soap, Recorder, Bear, Eggplant, Board Eraser, Coconut, Tape Measure/Ruler, Pig, Showerhead, Globe, Chips, Steak, Crosswalk Sign, Stapler, Camel, Formula 1, Pomegranate, Dishwasher, Crab, Hoverboard,
Meat ball, Rice Cooker, Tuba, Calculator, Papaya, Antelope, Parrot, Seal, Butterfly, Dumbbell, Donkey, Lion, Urinal, Dolphin, Electric Drill, Hair Dryer, Egg tart, Jellyfish, Treadmill, Lighter,
Grapefruit, Game board, Mop, Radish, Baozi, Target, French, Spring Rolls, Monkey, Rabbit, Pencil Case, Yak, Red Cabbage, Binoculars, Asparagus, Barbell, Scallop, Noddles, Comb, Dumpling, Oyster,
Table Tennis paddle, Cosmetics Brush/Eyeliner Pencil, Chainsaw, Eraser, Lobster, Durian, Okra, Lipstick, Cosmetics Mirror, Curling, Table Tennis
"""

CHANNEL = 16